#%RAML 1.0
title: sapi-greenfleet-accounts-maintenance
description: GreenFleet System API. Provides CRUD style access to MySQL data.

protocols:
  - HTTP
mediaType:
  - application/json

uses:
  lib: greenfleet-datatypes-library.raml

/accounts:
  get:
    displayName: Get accounts
    responses:
      200:
        body:
          application/json:
            type: lib.Account[]
      500:
        body:
          application/json:
            type: lib.ErrorResponse

  post:
    displayName: Create account
    body:
      application/json:
        type: lib.Account
    responses:
      201:
        body:
          application/json:
            type: lib.Account
      400:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/accounts/{id}:
  uriParameters:
    id:
      type: string
      required: true
  get:
    displayName: Get account by id
    responses:
      200:
        body:
          application/json:
            type: lib.Account
      404:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/maintenance:
  get:
    displayName: Get maintenance requests
    responses:
      200:
        body:
          application/json:
            type: lib.MaintenanceRequest[]
      500:
        body:
          application/json:
            type: lib.ErrorResponse

  post:
    displayName: Create maintenance request
    body:
      application/json:
        type: lib.MaintenanceRequest
    responses:
      201:
        body:
          application/json:
            type: lib.MaintenanceRequest
      400:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/maintenance/{id}:
  uriParameters:
    id:
      type: string
      required: true
  get:
    displayName: Get maintenance request by id
    responses:
      200:
        body:
          application/json:
            type: lib.MaintenanceRequest
      404:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse