#%RAML 1.0
title: sapi-greenfleet-accounts-maintenance
description: GreenFleet System API. Provides CRUD style access to MySQL data.

protocols:
  - HTTP
mediaType:
  - application/json

uses:
  lib: greenfleet-datatypes-library.raml

/accounts:  
  get:
    #Lista todas as accounts
    displayName: Get accounts
    description: Returns all registered accounts.
    responses:
      200:
        body:
          application/json:
            type: lib.Account[]
      500:
        body:
          application/json:
            type: lib.ErrorResponse

  post:
    #Adiciona novas accounts
    displayName: Create account
    description: Creates a new account.
    body:
      application/json:
        type: lib.Account
    responses:
      201:
        body:
          application/json:
            type: lib.Account
      400:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/accounts/{accountId}:
  uriParameters:
    accountId:
      type: string
      required: true
  get:
    displayName: Get account by id
    description: Returns a specific account.
    responses:
      200:
        body:
          application/json:
            type: lib.Account
      404:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/vehicles:
  get:
    displayName: Get vehicles
    description: Returns all vehicles. Can be filtered by status.
    queryParameters:
      status:
        type: string
        required: false
        example: inMaintenance
    responses:
      200:
        body:
          application/json:
            type: lib.Vehicle[]
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/vehicles/{vehicleId}:
  uriParameters:
    vehicleId:
      type: string
      required: true

  get:
    displayName: Get vehicle by id
    description: Returns a specific vehicle.
    responses:
      200:
        body:
          application/json:
            type: lib.Vehicle
      404:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/maintenance:
  get:
    displayName: Get maintenance requests
    description: Returns all maintenance requests.
    responses:
      200:
        body:
          application/json:
            type: lib.MaintenanceRequest[]
      500:
        body:
          application/json:
            type: lib.ErrorResponse

  post:
    displayName: Create maintenance request
    description: Creates a new maintenance request for a vehicle.
    body:
      application/json:
        type: lib.MaintenanceRequest
    responses:
      201:
        body:
          application/json:
            type: lib.MaintenanceRequest
      400:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse

/maintenance/{maintenanceId}:
  uriParameters:
    maintenanceId:
      type: string
      required: true
  get:
    displayName: Get maintenance request by id
    description: Returns a specific maintenance request.
    responses:
      200:
        body:
          application/json:
            type: lib.MaintenanceRequest
      404:
        body:
          application/json:
            type: lib.ErrorResponse
      500:
        body:
          application/json:
            type: lib.ErrorResponse